// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsdQXFFVqatgP6fQtJAK7Vh6Z3yg36pb4',
    appId: '1:125460317439:web:e46683587412b2c783b8ca',
    messagingSenderId: '125460317439',
    projectId: 'service-order-e3895',
    authDomain: 'service-order-e3895.firebaseapp.com',
    storageBucket: 'service-order-e3895.firebasestorage.app',
    measurementId: 'G-K7ZYG1G44Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAufPlv8QE7dOvIm8CTnewjafCAishP1fM',
    appId: '1:125460317439:android:f738aac208f8164c83b8ca',
    messagingSenderId: '125460317439',
    projectId: 'service-order-e3895',
    storageBucket: 'service-order-e3895.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx434p1vGOZkL7FN-3gN_fhMJvP1fgJ6M',
    appId: '1:125460317439:ios:d91bdfcc57ec208583b8ca',
    messagingSenderId: '125460317439',
    projectId: 'service-order-e3895',
    storageBucket: 'service-order-e3895.firebasestorage.app',
    iosBundleId: 'com.example.ordemServico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx434p1vGOZkL7FN-3gN_fhMJvP1fgJ6M',
    appId: '1:125460317439:ios:d91bdfcc57ec208583b8ca',
    messagingSenderId: '125460317439',
    projectId: 'service-order-e3895',
    storageBucket: 'service-order-e3895.firebasestorage.app',
    iosBundleId: 'com.example.ordemServico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsdQXFFVqatgP6fQtJAK7Vh6Z3yg36pb4',
    appId: '1:125460317439:web:bf3d416c249c246583b8ca',
    messagingSenderId: '125460317439',
    projectId: 'service-order-e3895',
    authDomain: 'service-order-e3895.firebaseapp.com',
    storageBucket: 'service-order-e3895.firebasestorage.app',
    measurementId: 'G-RRBTM22GX4',
  );
}
